logging:
  file:
    name: myapplication.log
---
spring:
    config:
        activate:
            on-profile: dev
server:
    port: 8001
---
spring:
    config:
        activate:
            on-profile: test
server:
    port: 9001
    